#!/bin/bash
# run this script with sudo
# sudo ./run <path to your ssh keys>
trap 'pkill ssh' INT TERM ERR
trap 'pkill ssh' EXIT
ssh -i $1 -L 5672:85.217.171.67:5672  root@85.217.171.67 -fN
sleep 5
python3 scan.py 
wait
